// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomMainMenu","status":true,"description":"Horizontal Title Menu v1.0.0","parameters":{}},
{"name":"InGameLoad","status":true,"description":"Adds \"Load\" to the in-game menu between Save and Game End without returning to title.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"MoreSaveSlots","status":true,"description":"Increases the maximum number of save slots to 256. Default is 20.","parameters":{}},
{"name":"BattleTransitions","status":true,"description":"Battle Shatter Transition — screen breaks into pieces and falls on encounter.","parameters":{}},
{"name":"TargetLeaderFirst","status":true,"description":"Enemies always target party member 1 (leader) for single/random single targets. Compatible with your provided game_code.js.","parameters":{}},
{"name":"Companion","status":true,"description":"Auto Attack & Protection v1.0.0","parameters":{}},
{"name":"Credits","status":true,"description":"Defines the internal text for Credits screen (used by HorizontalTitleMenuWithCredits.js)","parameters":{}}
];
